module.exports = {
  data: [
    {
      question:
        "Who was the brother of Mary and Martha, whom Jesus raised from the dead?",
      option1: "Lazarus",
      option2: "Jairus",
      option3: "Bartimaeus",
      option4: "Nicodemus",
      ans: 1,
    },
    {
      question: "Who was the woman at the well Jesus spoke to?",
      option1: "Samaritan woman",
      option2: "Syrophoenician woman",
      option3: "Canaanite woman",
      option4: "Phoenician woman",
      ans: 1,
    },
    {
      question: "Who was the high priest who put Jesus on trial?",
      option1: "Annas",
      option2: "Caiaphas",
      option3: "Aaron",
      option4: "Eli",
      ans: 2,
    },
    {
      question:
        "Who was the Roman centurion who declared, 'Truly this was the Son of God!' at Jesus' crucifixion?",
      option1: "Cornelius",
      option2: "Julius",
      option3: "Claudius",
      option4: "Unnamed centurion",
      ans: 4,
    },
    {
      question: "Who was the disciple who replaced Judas Iscariot?",
      option1: "Matthias",
      option2: "Bartholomew",
      option3: "Thaddaeus",
      option4: "Philip",
      ans: 1,
    },
    {
      question: "Who was the father of Isaac?",
      option1: "Abraham",
      option2: "Lot",
      option3: "Nahor",
      option4: "Terah",
      ans: 1,
    },
    {
      question: "Who was the king of Babylon who saw the writing on the wall?",
      option1: "Nebuchadnezzar",
      option2: "Belshazzar",
      option3: "Darius",
      option4: "Cyrus",
      ans: 2,
    },
    {
      question: "Who was the woman who hid the spies in Jericho?",
      option1: "Rahab",
      option2: "Deborah",
      option3: "Jael",
      option4: "Esther",
      ans: 1,
    },
    {
      question: "Who was the apostle known as 'the zealot'?",
      option1: "Simon",
      option2: "Jude",
      option3: "Matthew",
      option4: "Thaddaeus",
      ans: 1,
    },
    {
      question: "Who was the prophet who anointed Saul as king?",
      option1: "Samuel",
      option2: "Nathan",
      option3: "Elijah",
      option4: "Elisha",
      ans: 1,
    },
  ],
};
